import type { DashboardSnapshot } from '../types'

const factors = [
  {name:'Impact',weight:40,source:'PATH RULES + GPT-5.5',formula:'0.50 × Component importance + 0.30 × Change significance + 0.20 × Blast radius',details:[['Component importance','A deterministic path map scores ingestion/auth 10, feature flags 9, replay/core APIs 8, shared product logic 6, tooling 4, and docs 2. Unknown paths default to 4.'],['Change significance','GPT-5.5 scores what changed: 9–10 for a major capability or critical reliability/security fix, down to 1–2 for cosmetic or trivial work.'],['Blast radius','GPT-5.5 estimates reach: 10 affects most events/users/products, 7 an entire product, 4 one workflow, and 1 an isolated edge case.']],rollup:'The contributor score is the meaningful-PR-value-weighted average of contribution Impact scores.'},
  {name:'Complexity',weight:25,source:'GPT-5.5 + REPOSITORY EVIDENCE',formula:'0.35 × Logic + 0.30 × Architecture + 0.20 × Cross-component + 0.15 × Change scope',details:[['Logic','Reasoning difficulty, from simple CRUD/UI through business logic, distributed systems, concurrency, performance, and difficult correctness.'],['Architecture','Whether the change modifies important abstractions, APIs, schemas, protocols, or system behavior.'],['Cross-component','Breadth across code paths—for example frontend only is lower than a capture → Kafka → storage/query change.'],['Change scope','Changed files and paths support the judgment, but volume alone never counts as complexity.']],rollup:'The contributor score is the meaningful-PR-value-weighted average across classified contributions.'},
  {name:'Meaningful output',weight:20,source:'DETERMINISTIC AGGREGATION',formula:'Output = percentile(Σ PR value × confidence) × 10',details:[['Contribution value','Major feature 5; major bug/performance fix 4; normal feature/fix 3; useful refactor 2; tests/infrastructure 1–2; docs 0.5; generated/trivial 0.'],['Complete coverage','Every contribution receives a value. GPT refines bounded candidates; conventional-commit and path rules cover the rest.'],['Normalization','The total becomes a contributor percentile within the same 90-day population, so raw commit count does not define output.']],rollup:'Twenty typo commits cannot outweigh a smaller set of substantive shipped changes.'},
  {name:'Ownership',weight:15,source:'FULLY DETERMINISTIC',formula:'(0.40 × Frequency + 0.30 × Continuity + 0.30 × Component share) × Component importance',details:[['Frequency','The contributor’s percentile-ranked meaningful PR value within a component.'],['Continuity','Distinct active weeks divided by the 13-week window, scaled to 0–10.'],['Component share','The contributor’s share of all meaningful output in the component—not merely the share of their own work.'],['Importance weighting','Sustained ownership of ingestion or feature flags counts more than ownership of a peripheral tool.']],rollup:'The highest component score becomes Ownership, rewarding sustained depth rather than broad, shallow activity.'},
]

export function MethodologyDrawer({data,onClose}:{data:DashboardSnapshot;onClose:()=>void}){
  return <div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="drawer" role="dialog" aria-modal="true" aria-label="Methodology">
    <button className="close" onClick={onClose}>Close ×</button><p className="eyebrow">TRANSPARENT BY DESIGN</p><h2>How impact is calculated</h2><p>{data.methodology.summary}</p>
    <div className="weight-grid">{Object.entries(data.methodology.weights).map(([k,v])=><div key={k}><b>{v}%</b><span>{k}</span></div>)}</div>
    <div className="factor-list">{factors.map(factor=><section className="factor-card" key={factor.name}>
      <div className="factor-head"><div><span>{factor.source}</span><h3>{factor.name}</h3></div><b>{factor.weight}%</b></div><code>{factor.formula}</code>
      <dl>{factor.details.map(([term,description])=><div key={term}><dt>{term}</dt><dd>{description}</dd></div>)}</dl><p className="rollup">{factor.rollup}</p>
    </section>)}</div>
    <h3>Two-stage method</h3><ol><li>GPT-5.5 scores semantic signals and refines PR value for a contributor-balanced sample capped at 500 contributions.</li><li>Deterministic code covers the complete 90-day window, applies the formulas above, and selects the top five. The model never chooses the ranking.</li></ol>
    <h3>Guardrails</h3><p>Generated and docs-only changes stay deterministic. Diff size is context, never an impact or complexity metric.</p>
    <h3>Limitations</h3><ul>{data.methodology.limitations.map(x=><li key={x}>{x}</li>)}</ul>
  </aside></div>
}
